version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-cms}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST:-postgres_db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-cms}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-admin}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  postgres-data:
